name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get latest release
        id: latest_release
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r .tag_name)
          echo "Latest release: $LATEST_RELEASE"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump patch version
        id: bump_version
        run: |
          LATEST_VERSION=${{ steps.latest_release.outputs.LATEST_RELEASE }}
          IFS='.' read -ra VERSION_PARTS <<< "$LATEST_VERSION"
          PATCH_BUMP=$(( ${VERSION_PARTS[2]} + 1 ))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_BUMP"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create bundle zip
        run: zip -r bundle.zip *.wdl

      - name: Create Release
        run: gh release create ${{ steps.bump_version.outputs.NEW_VERSION }} mbin_nmdc.wdl bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}