name: WDL validation CI

on:
  pull_request:
    branches: master

jobs:
  run-miniwdl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # specify the Python version you need

    - name: Install JAWS
      run: |
        python -m pip install --upgrade pip
        pip install --target /global/cfs/cdirs/m3408/users/nmdcda  jaws-client --index-url https://code.jgi.doe.gov/api/v4/projects/312/packages/pypi/simple

    - name: Validate WDL
      run: |
        # Add the commands to run your MiniWDL workflow
        jaws validate mbin_nmdc.wdl

